# Adds namespace to all resources.
namespace: minio-controller-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: minio-controller-

resources:
  - namespace.yaml

secretGenerator:
  - name: secret
    literals:
      - endpoint=localhost:32000
      - user=minio
      - password=miniominio
    options:
      disableNameSuffixHash: true
