[env]
KUBECONFIG = "{{config_root}}/kubeconfig"
KIND_CLUSTER_NAME = "bucket-controller"

[vars]
container_tool = "docker"
image = "bucket-controller:latest"
ignore_not_found = "false"

[tools]
go = "1.23"

"aqua:jqlang/jq" = "1.7"
"aqua:kubernetes-sigs/kubebuilder" = "4.5"
"aqua:kubernetes-sigs/kind" = "0.26.0"
"aqua:kubernetes/kubectl" = "1.32"

"go:github.com/golangci/golangci-lint/cmd/golangci-lint" = "v1.63.4"
"go:sigs.k8s.io/kustomize/kustomize/v5" = "v5.5.0"
"go:sigs.k8s.io/controller-runtime/tools/setup-envtest" = "release-0.20"
"go:sigs.k8s.io/controller-tools/cmd/controller-gen" = "v0.17.1"
"aqua:helm/helm" = "3.16"

[tasks.build]
run = "go build -o bin/manager cmd/main.go"
outputs = ["bin/manager"]
alias = "b"
sources = ["**/*.go"]
depends = ["manifests", "generate", "fmt", "vet"]

[tasks.run]
run = "go run ./cmd/main.go"
depends = ["manifests", "generate", "fmt", "vet"]

[tasks.install]
depends = ["manifests"]
run = 'kustomize build config/crd | kubectl apply -f-'

[tasks.uninstall]
depends = ["manifests"]
run = 'kustomize build config/crd | kubectl delete --ignore-not-found={{vars.ignore_not_found}} -f-'

[tasks.generate]
run = 'controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."'

[tasks.manifests]
run = 'controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases'

[tasks.fmt]
run = 'go fmt ./...'

[tasks.vet]
run = 'go vet ./...'

[tasks.test]
depends = ["manifests", "generate", "fmt", "vet", "setup-envtest"]
run = ''

[tasks.lint]
run = 'golangci-lint run'

[tasks."lint:fix"]
run = 'golangci-lint run --fix'

[tasks."lint:config"]
run = 'golangci-lint config verify'

[tasks.setup-envtest-version]
run = '''{% raw %}go list -m -f "{{slice .Version 1 }}" sigs.k8s.io/controller-runtime{% endraw %} | cut -d. -f-2'''

[tasks."kind:create"]
run = "kind create cluster"

[tasks."kind:delete"]
run = "kind delete cluster"

[tasks."kind:load"]
run = "kind load docker-image {{vars.image}}"

[tasks."docker:build"]
run = "{{vars.container_tool}} build -t {{vars.image}} ."

[tasks."docker:push"]
run = "{{vars.container_tool}} push {{vars.image}}"

[tasks."minio:deploy"]
run = "kustomize build --enable-helm deploy/minio/ | k apply -f-"

[tasks."minio:teardown"]
run = "kustomize build --enable-helm deploy/minio/ | k delete -f-"
