apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio-controller
labels:
- includeSelectors: true
  pairs:
    app: minio-controller

resources:
  - namespace.yaml

secretGenerator:
  - name: minio
    literals:
      - endpoint=localhost:32000
      - user=minio
      - password=miniominio
    options:
      disableNameSuffixHash: true
