# This rule is not used by the project bucket-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the bucket.ixday.github.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: bucket-controller
    app.kubernetes.io/managed-by: kustomize
  name: minio-editor-role
rules:
- apiGroups:
  - bucket.ixday.github.io
  resources:
  - minios
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bucket.ixday.github.io
  resources:
  - minios/status
  verbs:
  - get
