# This rule is not used by the project minio-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to minio.ixday.github.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: minio-controller
    app.kubernetes.io/managed-by: kustomize
  name: policy-viewer-role
rules:
- apiGroups:
  - minio.ixday.github.io
  resources:
  - policies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - minio.ixday.github.io
  resources:
  - policies/status
  verbs:
  - get
