---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - bucket.ixday.github.io
  resources:
  - minios
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bucket.ixday.github.io
  resources:
  - minios/finalizers
  verbs:
  - update
- apiGroups:
  - bucket.ixday.github.io
  resources:
  - minios/status
  verbs:
  - get
  - patch
  - update
