---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - patch
  - update
  - watch
- apiGroups:
  - minio.ixday.github.io
  resources:
  - buckets
  - policies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - minio.ixday.github.io
  resources:
  - buckets/finalizers
  - policies/finalizers
  verbs:
  - update
- apiGroups:
  - minio.ixday.github.io
  resources:
  - buckets/status
  - policies/status
  verbs:
  - get
  - patch
  - update
