apiVersion: minio.ixday.github.io/v1alpha1
kind: Policy
metadata:
  labels:
    app.kubernetes.io/name: minio-controller
    app.kubernetes.io/managed-by: kustomize
  name: policy-sample
spec:
  bucketName: bucket-sample
  statements:
    - effect: Allow
      actions:
        - s3:ListBucket
        - s3:GetBucketLocation
        - s3:ListBucketMultipartUploads
    - effect: Allow
      subPaths: ["*"]
      actions:
        - s3:PutObject
        - s3:GetObject
        - s3:DeleteObject
        - s3:ListMultipartUploadParts
        - s3:AbortMultipartUpload
