apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio
labels:
- includeSelectors: true
  pairs:
    app: minio

resources:
  - namespace.yaml

secretGenerator:
  - name: minio
    literals:
      - rootUser=minio
      - rootPassword=miniominio
    options:
      disableNameSuffixHash: true

helmCharts:
- name: minio
  namespace: minio
  releaseName: minio
  repo: https://charts.min.io/
  version: 5.4.0
  valuesInline:
    mode: standalone
    existingSecret: "minio"
    service:
      type: NodePort
      nodePort: "32000"
    consoleService:
      type: NodePort
      nodePort: "32001"
    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2025-02-03T21-03-04Z
    persistence:
      size: 1Gi
    replicas: 1
    resources:
      requests:
        memory: 1Gi
    serviceAccount:
      name: minio
